local c = require("incorrectish_colors.colors")

return {
    normal = {
        bg = c.none,
        fg = c.light_grey,
    },
    ellipsis = { fg = c.grey },
    separator = { fg = c.grey },
    modified = { fg = c.green },
    dirname = {},
    basename = { fg = c.fg },
    context = {},
    context_file = { fg = c.blue },
    context_module = { fg = c.orange },
    context_namespace = { fg = c.orange },
    context_package = { fg = c.orange },
    context_class = { fg = c.yellow },
    context_method = { fg = c.blue },
    context_property = { fg = c.cyan },
    context_field = { fg = c.purple },
    context_constructor = { fg = c.blue },
    context_enum = { fg = c.purple },
    context_interface = { fg = c.green },
    context_function = { fg = c.blue },
    context_variable = { fg = c.purple },
    context_constant = { fg = c.orange },
    context_string = { fg = c.green },
    context_number = { fg = c.orange },
    context_boolean = { fg = c.orange },
    context_array = { fg = c.purple },
    context_object = { fg = c.purple },
    context_key = { fg = c.purple },
    context_null = { fg = c.red },
    context_enum_member = { fg = c.yellow },
    context_struct = { fg = c.purple },
    context_event = { fg = c.yellow },
    context_operator = { fg = c.red },
    context_type_parameter = { fg = c.red },
}
